name: KataBump Proxy Auto Renew

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1,13 * * *'

jobs:
  run-renew:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        # 核心：安装支持 SOCKS 代理的扩展包
        run: pip install requests[socks] pysocks

      - name: Run Script
        env:
          KATA_EMAIL: ${{ secrets.USER_EMAIL }}
          KATA_PASSWORD: ${{ secrets.USER_PASSWORD }}
          # 记得在 Secrets 中添加这个变量
          S5_PROXY: ${{ secrets.S5_PROXY }} 
          TG_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python katabump.py
